### ISSUE TITLE
The shipping cost is not calculating correctly in the Cart when increasing/decreasing the product quantity in the cart.

### ISSUE THREAD

**Issue by priyanka-tychesoftwares** [TycheSoftwares/currency-per-product-for-woocommerce#53]
**Describe the bug**
The shipping cost is not calculating correctly in the Cart when increasing/decreasing the product quantity in the cart.

**To Reproduce**
1. Add product to the cart.
2. Select the "Netherlands" as the shipping location on the cart page. The shipping cost will calculate as converted as 3,84.
3. Increase the product quantity to 2. The price will show as 4.60 which is originally set in WC Shipping cost.
4. If you decrease the product quantity then also the price is the same. 

**Expected behavior**
The shipping cost should calculate correctly in the Cart when increasing/decreasing the product quantity in the cart.

**Screenshots**

**Additional context**
https://tychesoftwares.freshdesk.com/a/tickets/32096

**Comment by gaminikhil** [comment]
I tried to replicate the issue at my end but unable to replicate the issue. We are not changing the shipping code based on the currency. No changes in the price, not matter in which currency the product is. Ideally we should calculate the shipping cost based on the currency in the cart otherwise in some case the shipping will be higher/lower depending on the currency which may cause loss/higher shipping cost.

**Comment by pinalj** [comment]
The client uses Flexible Shipping plugin which calculates shipping charges based on weight and/or cart total. The issue will have to be replicated using a similar setup.
I'm closing the existing PR as it is old and will need some rework.

**Comment by ashokrane** [comment]
@pinalj @upenkapse This issue is almost 2 years old. Can we close this issue for now & take it up if another client comes up with it? I am not sure of the ROI on spending time on this issue.

@gaminikhil Always try to replicate an issue with the setup as is mentioned in the Github issue & the ticket. Sometimes the Github issue may not contain all details. Please check the ticket in such cases to confirm the exact setup that the client had.

**Comment by pinalj** [comment]
Closing the issue without any fixes based on the above discussion. We will take it up when another client reports it.
